export const projects = [
  {
    id: 'playlistbridge',
    name: 'PlaylistBridge',
    tagline: 'Converts AI playlists into Spotify, YouTube Music & YouTube links instantly.',
    description: 'Zero login. Zero API keys from the user. Full PWA — works offline, installable on Android. Getting AI referral traffic via llms.txt. Built with a 3-layer cache and canvas image generation.',
    category: 'MUSIC TECH · FULL-STACK',
    url: 'https://playlistbridge.netlify.app',
    github: null,
    featured: true,
    stats: { label: 'Google Rank', value: '#1' },
    tags: ['Vanilla JS', 'YouTube IFrame API', 'Serverless Functions', 'PWA Offline', 'SEO #1', 'Canvas Image Gen', 'Short URLs', 'AI Traffic (llms.txt)'],
  },
  {
    id: 'rmsads',
    name: 'RMS Ads',
    tagline: 'Influencer ad platform for Telegram — live campaigns, real revenue.',
    description: 'Client-facing platform managing affiliate campaigns across multiple EdTech brands. Tracks conversions, generates revenue reports. Live with real clients and real earnings.',
    category: 'AD TECH · REVENUE PLATFORM',
    url: 'https://rmsads.com',
    github: null,
    featured: true,
    stats: { label: 'Status', value: 'LIVE' },
    tags: ['Firebase Backend', 'Affiliate Tracking', 'Multi-Brand Support', 'Real-Time Data', 'Client Dashboard', 'Live Revenue'],
  },
  {
    id: 'answerhunt',
    name: 'AnswerHunt',
    tagline: 'Reddit & forum insights aggregated into structured verdict pages.',
    description: 'Content platform with Insight Scores, Situation Filters, and community YES/NO debates. Live with Google AdSense revenue. SEO-architected from the ground up.',
    category: 'CONTENT · ADSENSE LIVE',
    url: 'https://answerhunt.com',
    github: null,
    featured: false,
    stats: { label: 'Revenue', value: 'ADSENSE' },
    tags: ['Firebase Voting', 'SEO Architecture', 'Verdict Pages', 'AdSense Revenue', 'Insight Scores'],
  },
  {
    id: 'smitos',
    name: 'SmitOS',
    tagline: 'This portfolio — a browser-based OS with full windowed environment.',
    description: 'React + Vite + Zustand. Draggable panels, app registry, schema-versioned persistence, mobile mode. Zero UI libraries.',
    category: 'PORTFOLIO · OS INTERFACE',
    url: null,
    github: null,
    featured: false,
    stats: { label: 'Status', value: 'IN DEV' },
    tags: ['React + Vite', 'Zustand State', 'Window Lifecycle', 'Schema Versioning', 'Drag + Resize'],
  },
];
